// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ_NEvLRJIrDAnZ2HxMGMg10eCmSMWinM',
    appId: '1:142207684839:android:5535488eeae013631ed242',
    messagingSenderId: '142207684839',
    projectId: 'dietx-df807',
    databaseURL: 'https://dietx-df807.firebaseio.com',
    storageBucket: 'dietx-df807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUy0SiKJBZGWIVTIYkreA3ZuJkIMHvp4s',
    appId: '1:142207684839:ios:a3d6aac153fec13a1ed242',
    messagingSenderId: '142207684839',
    projectId: 'dietx-df807',
    databaseURL: 'https://dietx-df807.firebaseio.com',
    storageBucket: 'dietx-df807.appspot.com',
    iosClientId: '142207684839-bd5tcl2op33jk976h97v2u5apb9201gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietx',
  );
}
